// <auto-generated />
namespace ImagineCupBTrees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rearrangedreadingsdevicessensorsandcommands : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rearrangedreadingsdevicessensorsandcommands));
        
        string IMigrationMetadata.Id
        {
            get { return "201702010202149_Rearranged readings, devices, sensors, and commands"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
